<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

# Exercise 1

subsetting: selection of one element
indexing: one element in a list/array/grp
slicing: selection fo a range of elements by slicing
masking: hide elements to produce a range of elements


# Exercise 2

In [3]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
a= np_array_2d[:,0]
a

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U21')

In [4]:
b = a.astype(int)
b

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [5]:
c = b % 2
c

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [6]:
d = c >0 
d

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [7]:
e = b [d]
e

array([1, 3, 5, 7, 9])

In [8]:
f = np_array_2d[e, 1]
f

array(['C', 'D', 'G', 'H', 'I'], dtype='<U21')

# Excercise 3

In [9]:
a = [[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]]

b = np.array(a)
b

array([[66, 50, 57, -1, -1],
       [92, -1, 88, -1, -1],
       [75, -1, -1, 76, -1],
       [-1, 51, 87, -1, -1],
       [71, -1, 67, -1, 69]])

In [11]:
m1 = (b < 50)
c = b
c[m1] = -1
c

m2 = (b > 50)
c[m2] = 1
c

m3 = (b == 50)
c[m3] = 0
c

array([[ 1,  0,  1, -1, -1],
       [ 1, -1,  1, -1, -1],
       [ 1, -1, -1,  1, -1],
       [-1,  1,  1, -1, -1],
       [ 1, -1,  1, -1,  1]])