<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

Subsetting means to ‘select’.
Indexing refers to selecting one element.
Slicing refers to selecting a range of elements.

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

slicing give range of elements; specify start and end using x[:]

In [5]:
import numpy as np

In [6]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

x = py_list

In [8]:
x[0]  #first element

'a1'

In [9]:
x[-1] #last element

'j10'

In [13]:
x[0:1] #gives 1-0 = 1 element

['a1']

In [16]:
x[1:6] #gives 6-1 = 5 element, starting from index 1

['b2', 'c3', 'd4', 'e5', 'f6']

In [17]:
x[1:6:2] #gives every other 6-1 = 5 element, starting from index 1

['b2', 'd4', 'f6']

In [19]:
x[:5] # gives len(x)-5 = 5; start from index 5 to the end

['a1', 'b2', 'c3', 'd4', 'e5']

In [21]:
x[5:2:-1] #gives 5-2 = 3 elements, done in reverse

['f6', 'e5', 'd4']

In [23]:
x[::-1] #reverses the whole list

['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']

slicing with [i:j] will give results starting with i and ending with j-1, giving you j-1 elements

## 1.2 Arrays only | Subsetting by masking

In [32]:
np_array = np.array([1,2,3,4,5,6,7,8,9,100])

In [37]:
my_mask = np_array > 3   #show if each element is >3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [40]:
np_array[my_mask] # for only the true ones

array([  4,   5,   6,   7,   8,   9, 100])

In [ ]:
#for more succinctness

In [41]:
np_array[np_array>3]

array([  4,   5,   6,   7,   8,   9, 100])

In [43]:
np_array[~(np_array>3)] # ~ means not, so it inverts >3

array([1, 2, 3])

In [44]:
np_array[(np_array > 3) & (np_array < 8)] # & means when both are true

array([4, 5, 6, 7])

In [45]:
np_array[(np_array < 3) | (np_array > 8)] # | means when element appear in either mask

array([  1,   2,   9, 100])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [46]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"], 
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [47]:
py_list_2d [3] #position 4

[4, 'D']

In [48]:
np_array_2d [3] #position 4

array(['4', 'D'], dtype='<U21')

In [49]:
py_list_2d [3] [1] #position 4 second element

'D'

In [50]:
np_array_2d [3, 0] #position 4 first element

np.str_('4')

In [51]:
py_list_2d[:3] # first 3 positions

[[1, 'A'], [2, 'B'], [3, 'C']]

In [52]:
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

In [53]:
py_list_2d[:3][0] # first 3 position firt element

array(['1', '2', '3'], dtype='<U21')

In [54]:
np_array_2d[:3, 0] # interestingly, gives same as above

array(['1', '2', '3'], dtype='<U21')

In [63]:
py_list_2d[3:6] [0] # only the first of positions 4, 5, 6

[4, 'D']

In [64]:
np_array_2d[3:6, 0] # only the first element of position 4,5,6

array(['4', '5', '6'], dtype='<U21')

In [59]:
np_array_2d[:, 0] # only the first element of all position

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

## 1.4 Growing lists

In [65]:
#large list from small
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [67]:
# grow list by appending one element at a time
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [68]:
# alternate ways to append:
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [71]:
#append function, which runs 1.5x faster than the rest
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

In [ ]:
#to incorperate multiple elements, use can extend() and append()

In [72]:
x = [1, 2, 3]
x += [4, 5, 6]
x

[1, 2, 3, 4, 5, 6]

In [73]:
x=[1, 2, 3]
x.extend([4, 5, 6])
x

[1, 2, 3, 4, 5, 6]

In [74]:
x=[1, 2, 3]
x.append([4, 5, 6])
x
#the appended parts are bracketed

[1, 2, 3, [4, 5, 6]]

# Some loose ends

## 1.5 Tuples

In [75]:
a=(1, 2, 3)     # defining tuple

In [77]:
print(a[0]) # access data
print (a[2])

1
3


In [79]:
a[0]=-1
a[0]+= [10] #cannot work because cannot change the data inside

TypeError: 'tuple' object does not support item assignment

## 1.6 Be VERY careful when copying

In [80]:
x=[1, 2, 3]
y=x          
z=x         #these are wrong

In [81]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

## Footnotes