<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

In [1]:
import numpy as np


# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

In [2]:
py_super_names = ["Black widow", "Iron Man", "Doctor Strange"]     # python lists
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephan Strange"]

In [3]:
np_super_names = ["Black widow", "Iron Man", "Doctor Strange"]     # numpy lists
np_real_names = ["Natasha Romanoff", "Tony Stark", "Stephan Strange"]

In [4]:
superhero_info = {                               # dictionary lists
    "Natasha Romanoff" : "Black Widow", 
    "Tony Stark" : "Iron Man" ,
    "Doctor Strange" : "Stephan Strange"
    }

extra info
- dictionary have key and associated value seperated by a:
- dictionary elegantly holds real and superhero names in one
- py list/np arrays: order matters (eg, iron man and tony stark should be in the same position)

## 1.2 Accessing data from a list (or array)

access data by the index corresponding to data's position. start counting at 0

In [5]:
py_real_names [0]  

'Natasha Romanoff'

In [6]:
py_real_names [2]     #forward indexing

'Stephan Strange'

In [7]:
py_real_names [-1]  #reverse indexing, -1 starts instead of 0

'Stephan Strange'

## 1.3 Accessing data from a dictionary

In [8]:
superhero_info ["Natasha Romanoff"]

'Black Widow'

Values with dictionary are paired with a key, ie the first item

In [9]:
superhero_info.keys() # to access all keys

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Doctor Strange'])

In [10]:
superhero_info.values() # to access all values

dict_values(['Black Widow', 'Iron Man', 'Stephan Strange'])

## 1.4 Higher dimensional lists

can store more with 2 dimentional lists. use a new line for each different type of object

In [11]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

In [12]:
py_superhero_info [0]

['Natasha Romanoff', 'Black Widow']

# 2 Lists vs. Arrays

## 2.1 Size

use len() to figure out how many elements are in a list

In [18]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

len(py_list_2d)

10

In [24]:
np_array_2d = np.array(py_list_2d)  

len(np_array_2d)

10

In [25]:
# for the shape of np
np_array_2d.shape

(10, 2)

## 2.2 Arrays are fussy about type

array only have 1 single data type, while list is more accomdating 

In [26]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [27]:
py_list

[1, 1.5, 'A']

In [28]:
np_array

array(['1', '1.5', 'A'], dtype='<U32')

can change type using astypes()

## 2.3 Adding a number

In [29]:
py_list = [1,2,3,4,5]
np_array = np.array(py_list)

In [30]:
np_array + 10

array([11, 12, 13, 14, 15])

In [33]:
py_list + 10 # won't work, so to do this might need to convert first

TypeError: can only concatenate list (not "int") to list

## 2.4 Adding another list

In [35]:
py_list_1 = [1,2,3,4,5]
py_list_2 = [10,20,30,40,50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [36]:
py_list_1 + py_list_2 # combine the lists based on each individual number

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [37]:
np_array_1 + np_array_2 # combines by adding the corressponding number 
                        # in each position

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [39]:
py_list = [1,2,3,4]
np_array = np.array(py_list)

In [40]:
py_list*2 # gives all data points x2

[1, 2, 3, 4, 1, 2, 3, 4]

In [41]:
np_array*2 # gives x2 of each element 

array([2, 4, 6, 8])

## 2.6 Squaring

In [44]:
py_list**2 # no work

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [47]:
np_array**2 # yay works

array([ 1,  4,  9, 16])

## 2.7 Asking questions

In [48]:
py_list ==3  # based on sum of numbers

False

In [50]:
np_array ==3 # based on each data point

array([False, False,  True, False])

In [51]:
py_list > 3 #why don't want work :(

TypeError: '>' not supported between instances of 'list' and 'int'

In [53]:
np_array > 3 # based on each data point

array([False, False, False,  True])

## 2.8 Mathematics

py_list functions:

In [59]:
sum(py_list) # sum of all the numbers

10

In [60]:
max(py_list) # biggest number in the list

4

In [61]:
min(py_list) #s smallest no

1

note: py_list.sum() wont work

np_array functions:

In [62]:
np_array.sum()

np.int64(10)

In [63]:
np_array.max()

np.int64(4)

In [64]:
np_array.min()

np.int64(1)

In [65]:
np_array.mean()

np.float64(2.5)

In [66]:
np_array.std()

np.float64(1.118033988749895)

## Footnotes